// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6z27IPEEB73OzPmvYqXKnwDF6CfXHNQs',
    appId: '1:776206258018:web:0a472b4192fcc71ed8663b',
    messagingSenderId: '776206258018',
    projectId: 'contador-com-login-78743',
    authDomain: 'contador-com-login-78743.firebaseapp.com',
    storageBucket: 'contador-com-login-78743.firebasestorage.app',
    measurementId: 'G-EDTT271CR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-w5Bk7ouIQah1APxAbhBK8Z_Y3RmrOY',
    appId: '1:776206258018:android:c4123a51549cabfad8663b',
    messagingSenderId: '776206258018',
    projectId: 'contador-com-login-78743',
    storageBucket: 'contador-com-login-78743.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceCqDW2-pbpMf_JlUQOH36sG2GPzUo_A',
    appId: '1:776206258018:ios:cb73cc1f5cc6b4f5d8663b',
    messagingSenderId: '776206258018',
    projectId: 'contador-com-login-78743',
    storageBucket: 'contador-com-login-78743.firebasestorage.app',
    iosBundleId: 'com.example.contadorComLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceCqDW2-pbpMf_JlUQOH36sG2GPzUo_A',
    appId: '1:776206258018:ios:cb73cc1f5cc6b4f5d8663b',
    messagingSenderId: '776206258018',
    projectId: 'contador-com-login-78743',
    storageBucket: 'contador-com-login-78743.firebasestorage.app',
    iosBundleId: 'com.example.contadorComLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6z27IPEEB73OzPmvYqXKnwDF6CfXHNQs',
    appId: '1:776206258018:web:5290579aa67aa685d8663b',
    messagingSenderId: '776206258018',
    projectId: 'contador-com-login-78743',
    authDomain: 'contador-com-login-78743.firebaseapp.com',
    storageBucket: 'contador-com-login-78743.firebasestorage.app',
    measurementId: 'G-VP6RWSD7B7',
  );
}
